[package]
name = "incremental_bounding_computations"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
adapton = "0.3.31"
depends = "0.10.2"
nannou = "0.19"
